### ISSUE TITLE
Broken links in step 4

### ISSUE THREAD

**Issue by ryrob30** [AdobeDocs/target.en#158]
Issue in ./help/c-integrating-target-with-mac/a4t/a4timplementation.md

The links to AA documentation get redirected to the experience league home page.

**Comment by mtalbot29** [comment]
Thanks. Should be fixed. You might need to refresh your browser.

https://experienceleague.adobe.com/docs/target/using/integrate/a4t/a4timplementation.html?lang=en#integrate

I think the Analytics writers rearranged their guides. Unfortunately, broken links are redirected to ExpL, rather than reporting a broken link during build.

Thanks again.
