### ISSUE TITLE
add a FAQ about changing traffic splits in A4T activity

### ISSUE THREAD

**Issue by kwarner-adobe** [AdobeDocs/target.en#20]
Issue in ./help/c-integrating-target-with-mac/a4t/r-a4t-faq/a4t-faq-viewing-reports.md

From clientcare in response to a customer ticket:
Question: "Can I change the traffic % splits in an A4T activity after activation?"
Answer: [this text is straight from clientcare. It needs a lot of improvement: "Switching splits in the same A4T activity will cause some weird splits in Analytics because the visitor id will persist the target experience through for the persisting time like 30 or 90 days. the split would only impact net new visitors not any of the persisting ones.  I think this is just a bad workflow, if you want to change the split, highly recommend stopping the activity and making a new one that way the new activity id will start with a fresh visitors and you don't have to worry about the previous persistent baggage that comes with it."

Can you add this?

**Comment by mtalbot29** [comment]
https://docs.adobe.com/content/help/en/target/using/integrate/a4t/a4t-faq/a4t-faq-viewing-reports.html#can-i-change-the-percentage-of-traffic-allocation-in-an-activity-that-uses-a4t-after-the-activity-has-been-activated

**Can I change the percentage of traffic allocation in an activity that uses A4T after the activity has been activated?**

Changing the traffic allocation percentage in an activity after activation can cause inconsistent reporting in Analytics because the change impacts only new visitors. Returning visitors are not impacted.

As best practice, you should stop the existing activity and then create a new activity instead of changing the percentage after activation. Reporting for the new activity starts with new visitors and data from returning visitors will not cause inconsistent reporting.
